### ISSUE TITLE
Questions about the direction of particle flow

### ISSUE THREAD

**Issue by yvonne20061** [RaymanNg/3D-Wind-Field#32]
Can you please help answer my questions about the direction of particle flow, as follows, thank you very much!

1. I noticed that the particle flow started in this direction. Is this correct?

![擷取](https://user-images.githubusercontent.com/54659675/76718053-7418c580-6770-11ea-9822-e4e9679f34d2.JPG)

2.  Why does the particle flow turn almost 90 degrees? Shouldn't it be smooth?

![擷取1](https://user-images.githubusercontent.com/54659675/76718182-e25d8800-6770-11ea-879e-d816548af579.JPG)

**Comment by RaymanNg** [comment]
> I noticed that the particle flow started in this direction. Is this correct?

Yes, you can determine the direction by the fade out.

> Why does the particle flow turn almost 90 degrees? Shouldn't it be smooth?

Did that happen after you zoom in the camera? If so, this demo can not support zooming in too much...

~~I totally agree that the trails should be smooth, but due to the numerical precision of WebGL, it may be complicate to make it absolutely smooth.~~

If you think this is not caused by the numerical precision limitation, feel free to discuss here.

**Comment by yvonne20061** [comment]
> Yes, you can determine the direction by the fade out. 

How can I determine the direction? Which file should I modify? 
I don't want the particle flow to turn at the beginning.

> Did that happen after you zoom in the camera? If so, this demo can not support zooming in too much...

Yes, that became more obvious after I zoomed in the camera:(

**Comment by RaymanNg** [comment]
> How can I determine the direction? Which file should I modify?
> I don't want the particle flow to turn at the beginning.

If you want to control the direction, there is no direct way to do that, but you can control the direction by controlling the particles movement(nextSpeed and nextPosition).

P.S. It suddenly occurs to me that your problem may have something to do with the [distortion](https://en.wikipedia.org/wiki/Map_projection#Distortion). You may want to know about it. I did think about solving the distortion problem but I am not good at math...

**Comment by yvonne20061** [comment]
I am not good at math too :`(
If I can find the solution, I will share with you~
Thank you so much for your reply and advice!!

**Comment by RaymanNg** [comment]
After some investigation, I realized that I did not reset the particles speed when refreshing particles, which should be the root cause of your problem....

Now I have committed a fix for that, you can check out the latest code to check if your problem is solved.

Sorry for my misleading claims about "numerical precision" and "distortion", they should not be the main causes of this problem.

**Comment by yvonne20061** [comment]
> Now I have committed a fix for that, you can check out the latest code to check if your problem is solved.

Thanks!!! It solved my first problem.

> Why does the particle flow turn almost 90 degrees? Shouldn't it be smooth?

But this problem still exists :(

**Comment by RaymanNg** [comment]
> But this problem still exists :(

Where did you find this? Could you provide the location (latitude longitude) ?

**Comment by yvonne20061** [comment]
It is near Taiwan.
![image](https://user-images.githubusercontent.com/54659675/76937218-5cd40680-692f-11ea-8e27-7ad67b52164b.png)
If you zoom in you will see.

**Comment by RaymanNg** [comment]
1. The algorithm for updating speed and position in this demo is simple,  maybe using a more complex math method will give you a better visualization result.
2. Even if you make use of a more proper algorithm, I think it is normal for particles to have a sudden turn if the wind force is strong enough

**Comment by RaymanNg** [comment]
How I update speed in this demo:
`nextSpeed = currentSpeed + getWind(currentPosition)`

How I update position in this demo:
`nextPosition = currentPosition + currentSpeed`

I think I oversimplify the calculation and the position and speed should be calculated by solving the differential equations through some numerical methods. You may want to have a try, or you can try to remove the particle speed, only use the wind to update the position so that `nextPosition = currentPosition + getWind(currentPosition)`

**Comment by yvonne20061** [comment]
Thank you for your reply. I encountered another problem.

I tried to load the flow data, and the result was wrong:(
![image](https://user-images.githubusercontent.com/54659675/78746931-b5307e00-799a-11ea-8b5f-5e6524e2cec5.png)

This is the right direction. ↓
![image](https://user-images.githubusercontent.com/54659675/78746994-dabd8780-799a-11ea-82e5-d1783e6e3dfc.png)

The data contains a lot of uv vectors that are zero.
Is it possible for this reason?

**Comment by RaymanNg** [comment]
I think below are the root causes:

> How I update speed in this demo:
> nextSpeed = currentSpeed + getWind(currentPosition)
> 
> How I update position in this demo:
> nextPosition = currentPosition + currentSpeed

The trails I draw is more like the movement trails of particles, it is different from the wind direction.
It is definitely possible for a particle to move against the wind, just like a car can run against the wind. 

Of course, you can use a different formula to draw trails of wind direction

**Comment by Amber-372** [comment]
> Thank you for your reply. I encountered another problem.
> 
> I tried to load the flow data, and the result was wrong:(
> ![image](https://user-images.githubusercontent.com/54659675/78746931-b5307e00-799a-11ea-8b5f-5e6524e2cec5.png)
> 
> This is the right direction. ↓
> ![image](https://user-images.githubusercontent.com/54659675/78746994-dabd8780-799a-11ea-82e5-d1783e6e3dfc.png)
> 
> The data contains a lot of uv vectors that are zero.
> Is it possible for this reason?

Did you solve this problem？I have the same problem.

**Comment by RaymanNg** [comment]
Hi, I just committed a fix to correct the direction, could you pull the latest code and have a try?
